name: Static code analysis

on: [push]

jobs:
  static-code-analysis:
    container: zdenekdrahos/phpqa:v1.23.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: phpqa
        run: phpqa
